DROP TABLE UTILISER;
DROP TABLE CONCERNER;
DROP TABLE CONTENIR;
DROP TABLE COMMANDES;
DROP TABLE COMPOSITIONS;
DROP TABLE FLEURS;
DROP TABLE RECETTES;
DROP TABLE CLIENTS;
DROP TABLE GROUPES_REMISES;

CREATE TABLE CLIENTS ( 
	CLT_ID            	NUMBER NOT NULL,
	CLT_NOM           	VARCHAR2(50) NOT NULL,
	CLT_PRENOM        	VARCHAR2(50) NOT NULL,
	CLT_CODEPOSTAL    	CHAR(5) NOT NULL,
	CLT_VILLE         	VARCHAR2(50) NULL,
	CLT_TELEPHONE     	CHAR(14) NULL,
	CLT_PORTABLE      	CHAR(14) NULL,
	CLT_IDGROUPEREMISE	NUMBER DEFAULT NULL NULL 
	);
CREATE TABLE COMMANDES ( 
	CDE_ID      	NUMBER NOT NULL,
	CDE_DATE    	DATE NOT NULL,
	CDE_TOTALTTC	NUMBER(14,2) NOT NULL,
	CDE_IDCLIENT	NUMBER NOT NULL 
	);
CREATE TABLE COMPOSITIONS ( 
	COMP_ID          	NUMBER NOT NULL,
	COMP_LIBELLE     	VARCHAR2(100) NOT NULL,
	COMP_CODEARTICLE 	VARCHAR2(10) NOT NULL,
	COMP_PRIXVENTETTC	NUMBER(14,2) NOT NULL,
	COMP_IDRECETTE   	NUMBER DEFAULT NULL NULL 
	);
CREATE TABLE CONCERNER ( 
	CONC_IDCOMMANDE   	NUMBER NOT NULL,
	CONC_IDCOMPOSITION	NUMBER NULL,
	CONC_IDFLEUR      	NUMBER NULL,
	CONC_QUANTITE     	NUMBER(10,0) NOT NULL 
	);
CREATE TABLE CONTENIR ( 
	CONT_IDFLEUR      	NUMBER NULL,
	CONT_IDCOMPOSITION	NUMBER NOT NULL,
	CONT_QUANTITE     	NUMBER(10,0) NOT NULL 
	);
CREATE TABLE FLEURS ( 
	FLR_ID          	NUMBER NOT NULL,
	FLR_CODEARTICLE 	VARCHAR2(10) NOT NULL,
	FLR_NOM         	VARCHAR2(100) NOT NULL,
	FLR_DESCRIPTION 	VARCHAR2(4000) NOT NULL,
	FLR_CONSEILS    	VARCHAR2(4000) NULL,
	FLR_PRIXVENTETTC	NUMBER(14,2) DEFAULT 0.0 NOT NULL 
	);
CREATE TABLE GROUPES_REMISES ( 
	GRP_ID        	NUMBER NOT NULL,
	GRP_REFERENCE 	CHAR(1) NOT NULL,
	GRP_LIBELLE   	VARCHAR2(50) NOT NULL,
	GRP_TAUXREMISE	NUMBER(5,2) NOT NULL 
	);
CREATE TABLE RECETTES ( 
	REC_ID          	NUMBER NOT NULL,
	REC_DESCRIPTION 	VARCHAR2(4000) NULL,
	REC_DATECREATION	DATE NOT NULL 
	);
CREATE TABLE UTILISER ( 
	UTIL_IDFLEUR  	NUMBER NULL,
	UTIL_IDRECETTE	NUMBER NOT NULL,
	UTIL_QUANTITE 	NUMBER(10,0) NOT NULL 
	);

ALTER TABLE CLIENTS
	ADD ( PRIMARY KEY (CLT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE );
ALTER TABLE COMMANDES
	ADD ( PRIMARY KEY (CDE_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE );
ALTER TABLE COMPOSITIONS
	ADD ( PRIMARY KEY (COMP_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE );
ALTER TABLE FLEURS
	ADD ( PRIMARY KEY (FLR_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE );
ALTER TABLE GROUPES_REMISES
	ADD ( PRIMARY KEY (GRP_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE );
ALTER TABLE RECETTES
	ADD ( PRIMARY KEY (REC_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE );
ALTER TABLE GROUPES_REMISES
	ADD ( CONSTRAINT CHK_TAUX
	CHECK (grp_tauxremise BETWEEN 0 AND 50)
	NOT DEFERRABLE INITIALLY IMMEDIATE );
ALTER TABLE CLIENTS
	ADD ( CONSTRAINT FK_CLI_GRP
	FOREIGN KEY(CLT_IDGROUPEREMISE)
	REFERENCES GROUPES_REMISES(GRP_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE COMMANDES
	ADD ( CONSTRAINT FK_CDE_CLT
	FOREIGN KEY(CDE_IDCLIENT)
	REFERENCES CLIENTS(CLT_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE COMPOSITIONS
	ADD ( CONSTRAINT FK_COMP_REC
	FOREIGN KEY(COMP_IDRECETTE)
	REFERENCES RECETTES(REC_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE CONCERNER
	ADD ( CONSTRAINT FK_CONC_FLR
	FOREIGN KEY(CONC_IDFLEUR)
	REFERENCES FLEURS(FLR_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE CONCERNER
	ADD ( CONSTRAINT FK_CONC_COMP
	FOREIGN KEY(CONC_IDCOMPOSITION)
	REFERENCES COMPOSITIONS(COMP_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE CONCERNER
	ADD ( CONSTRAINT FK_CONC_CDE
	FOREIGN KEY(CONC_IDCOMMANDE)
	REFERENCES COMMANDES(CDE_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE CONTENIR
	ADD ( CONSTRAINT FK_CONT_FLR
	FOREIGN KEY(CONT_IDFLEUR)
	REFERENCES FLEURS(FLR_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE CONTENIR
	ADD ( CONSTRAINT FK_CONT_COMP
	FOREIGN KEY(CONT_IDCOMPOSITION)
	REFERENCES COMPOSITIONS(COMP_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE UTILISER
	ADD ( CONSTRAINT FK_UTIL_REC
	FOREIGN KEY(UTIL_IDRECETTE)
	REFERENCES RECETTES(REC_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
ALTER TABLE UTILISER
	ADD ( CONSTRAINT FK_UTIL_FLR
	FOREIGN KEY(UTIL_IDFLEUR)
	REFERENCES FLEURS(FLR_ID)
	NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE );
