INSERT INTO GROUPES_REMISES(GRP_ID, GRP_REFERENCE, GRP_LIBELLE, GRP_TAUXREMISE)
  VALUES(1, 'A', 'Groupe A', 5);
INSERT INTO GROUPES_REMISES(GRP_ID, GRP_REFERENCE, GRP_LIBELLE, GRP_TAUXREMISE)
  VALUES(2, 'B', 'Groupe B', 12);
INSERT INTO GROUPES_REMISES(GRP_ID, GRP_REFERENCE, GRP_LIBELLE, GRP_TAUXREMISE)
  VALUES(3, 'C', 'Groupe C', 24);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(1, 'PATAMOB', 'Adhémar', '33000', 'BORDEAUX', '05-56-56-56-56', '06-06-06-06-08', 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(2, 'ZEUBLOUSE', 'Agathe', '33000', 'BORDEAUX', '02-41-33-31-18', '06-08-06-08-70', 1);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(3, 'KUZBIDON', 'Alex', '33000', 'BORDEAUX', '05-47-46-58-96', '06-06-06-06-08', NULL);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(4, 'LOCALE', 'Anasthasie', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(5, 'TEUTMARONNE', 'Armand', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(6, 'ZOUDANLKOU', 'Debbie', '33000', 'BORDEAUX', NULL, '06-05-58-89-69', NULL);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(7, 'RIVENBUSSE', 'Elsa', '33000', 'BORDEAUX', '05-45-85-85-96', NULL, 1);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(8, 'ARDELPIC', 'Helmut', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(9, 'VRANTE', 'Héléna', '33000', 'BORDEAUX', NULL, '06-23-25-65-65', 2);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(10, 'ENFAILLITE', 'Mélusine', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(11, 'EURKETUMEME', 'Odile', '33000', 'BORDEAUX', '08-60-90-90-99', NULL, NULL);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(12, 'HOTDEUGOU', 'Olaf', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(13, 'ODLAVIELLE', 'Pacôme', '33000', 'BORDEAUX', NULL, '06-58-56-25-05', 1);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(14, 'AMARTAKALDIRE', 'Quentin', '33000', 'BORDEAUX', NULL, NULL, 2);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(15, 'PEURSCONLA', 'Humphrey', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(16, 'TRAIBIEN', 'Samira', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(17, 'FONFEC', 'Sophie', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(18, 'FAIRANT', 'Teddy', '33000', 'BORDEAUX', NULL, NULL, NULL);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(19, 'BLAIREUR', 'Terry', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(20, 'AJERRE', 'Tex', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(21, 'CHMONFISSE', 'Thierry', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(22, 'PHOTOTETEDEMORT', 'Thomas', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(23, 'KAECOUTE', 'Xavier', '33000', 'BORDEAUX', NULL, NULL, NULL);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(24, 'ADROUILLE-TOULTAN', 'Yves', '33000', 'BORDEAUX', NULL, NULL, 1);
INSERT INTO CLIENTS(CLT_ID, CLT_NOM, CLT_PRENOM, CLT_CODEPOSTAL, CLT_VILLE, CLT_TELEPHONE, CLT_PORTABLE, CLT_IDGROUPEREMISE)
  VALUES(25, 'ANCHIER', 'Yvon', '33000', 'BORDEAUX', NULL, NULL, 3);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(1, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 1348, 2);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(2, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 10862.5, 5);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(3, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 72331.84, 4);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(4, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 1348, 13);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(5, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 10862.5, 15);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(6, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 72331.84, 22);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(7, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 8968, 1);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(8, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 58882, 8);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(9, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 64008, 12);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(10, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 2296, 15);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(11, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 152633, 16);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(12, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 16933, 1);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(13, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 51240, 17);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(14, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 30, 19);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(15, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 75, 19);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(16, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 728, 21);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(17, TO_DATE('2008-09-17 18:31:10','YYYY-MM-DD HH24:MI:SS'), 490, 21);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(18, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 20, 3);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(19, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 8200, 10);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(20, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 5.7, 18);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(21, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 187.2, 23);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(22, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 10862.5, 25);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(23, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 1400, 24);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(24, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 1152, 7);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(25, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 3120, 14);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(26, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 5605, 9);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(27, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 6785, 20);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(28, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 10915, 21);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(29, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 3870, 1);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(30, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 18615, 17);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(31, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 19152, 19);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(32, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 11340, 19);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(33, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 42775, 21);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(34, TO_DATE('2008-09-17 18:36:21','YYYY-MM-DD HH24:MI:SS'), 28938, 21);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(35, TO_DATE('2008-09-17 18:36:52','YYYY-MM-DD HH24:MI:SS'), 0.8, 11);
INSERT INTO COMMANDES(CDE_ID, CDE_DATE, CDE_TOTALTTC, CDE_IDCLIENT)
  VALUES(36, TO_DATE('2008-09-17 18:36:52','YYYY-MM-DD HH24:MI:SS'), 0.82, 6);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(1, '21 Roses Rouges', 'C_RR210001', 14, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(2, '21 Roses Blanches', 'C_RB210001', 15, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(3, '60 Roses Variées', 'C_60RV0001', 43, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(4, '60 Roses Variées', 'C_60RV0002', 42, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(5, '60 Roses Variées', 'C_60RV0003', 42, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(6, '60 Roses Variées', 'C_60RV0004', 42, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(7, '60 Roses Variées', 'C_60RV0005', 42, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(8, '60 Roses Variées', 'C_60RV0006', 42, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(9, 'Safran XXL - 51 Roses jaunes et oranges', 'C_SAF00001', 36, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(10, '60 Roses Equateur Variées', 'C_60RVE001', 60, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(11, '60 Roses Equateur Variées', 'C_60RVE002', 59, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(12, '60 Roses Equateur Variées', 'C_60RVE003', 59, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(13, '60 Roses Equateur Variées', 'C_60RVE004', 59, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(14, '60 Roses Equateur Variées', 'C_60RVE005', 60, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(15, '60 Roses Equateur Variées', 'C_60RVE006', 59, NULL);
INSERT INTO COMPOSITIONS(COMP_ID, COMP_LIBELLE, COMP_CODEARTICLE, COMP_PRIXVENTETTC, COMP_IDRECETTE)
  VALUES(16, 'Safran XXL - 51 Roses Equateur jaunes et oranges', 'C_SAFE0001', 51, NULL);
INSERT INTO FLEURS(FLR_ID, FLR_CODEARTICLE, FLR_NOM, FLR_DESCRIPTION, FLR_CONSEILS, FLR_PRIXVENTETTC)
  VALUES(1, 'RROUGE0001', 'Rose Rouge', 'Rose Rouge Locale', NULL, 0.78);
INSERT INTO FLEURS(FLR_ID, FLR_CODEARTICLE, FLR_NOM, FLR_DESCRIPTION, FLR_CONSEILS, FLR_PRIXVENTETTC)
  VALUES(2, 'RBLANC0001', 'Rose Blanche', 'Rose Blanche Locale', NULL, 0.82);
INSERT INTO FLEURS(FLR_ID, FLR_CODEARTICLE, FLR_NOM, FLR_DESCRIPTION, FLR_CONSEILS, FLR_PRIXVENTETTC)
  VALUES(3, 'RJAUNE0001', 'Rose Jaune', 'Rose Jaune Locale', NULL, 0.8);
INSERT INTO FLEURS(FLR_ID, FLR_CODEARTICLE, FLR_NOM, FLR_DESCRIPTION, FLR_CONSEILS, FLR_PRIXVENTETTC)
  VALUES(4, 'RORANGE001', 'Rose Orange', 'Rose Orange Locale', NULL, 0.8);
INSERT INTO FLEURS(FLR_ID, FLR_CODEARTICLE, FLR_NOM, FLR_DESCRIPTION, FLR_CONSEILS, FLR_PRIXVENTETTC)
  VALUES(5, 'RROSE00001', 'Rose Rose', 'Rose Rose Locale', NULL, 0.78);
INSERT INTO FLEURS(FLR_ID, FLR_CODEARTICLE, FLR_NOM, FLR_DESCRIPTION, FLR_CONSEILS, FLR_PRIXVENTETTC)
  VALUES(6, 'REROUGE001', 'Rose Equateur Rouge', 'Rose à très gros boutons, classée comme la plus belle rose du monde', NULL, 1.1);
INSERT INTO FLEURS(FLR_ID, FLR_CODEARTICLE, FLR_NOM, FLR_DESCRIPTION, FLR_CONSEILS, FLR_PRIXVENTETTC)
  VALUES(7, 'REBLANC001', 'Rose Equateur Blanche', 'Rose à très gros boutons, classée comme la plus belle rose du monde', NULL, 1.14);
INSERT INTO FLEURS(FLR_ID, FLR_CODEARTICLE, FLR_NOM, FLR_DESCRIPTION, FLR_CONSEILS, FLR_PRIXVENTETTC)
  VALUES(8, 'REJAUNE001', 'Rose Equateur Jaune', 'Rose à très gros boutons, classée comme la plus belle rose du monde', NULL, 1.12);
INSERT INTO FLEURS(FLR_ID, FLR_CODEARTICLE, FLR_NOM, FLR_DESCRIPTION, FLR_CONSEILS, FLR_PRIXVENTETTC)
  VALUES(9, 'REORANGE01', 'Rose Equateur Orange', 'Rose à très gros boutons, classée comme la plus belle rose du monde', NULL, 1.12);
INSERT INTO FLEURS(FLR_ID, FLR_CODEARTICLE, FLR_NOM, FLR_DESCRIPTION, FLR_CONSEILS, FLR_PRIXVENTETTC)
  VALUES(10, 'REROSE0001', 'Rose Equateur Rose', 'Rose à très gros boutons, classée comme la plus belle rose du monde', NULL, 1.1);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(1, NULL, 3, 1685);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(2, NULL, 6, 9875);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(3, NULL, 9, 64582);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(4, NULL, 3, 1685);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(5, NULL, 6, 9875);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(6, NULL, 9, 64582);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(7, 13, NULL, 152);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(8, 13, NULL, 998);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(9, 4, NULL, 1524);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(10, 1, NULL, 164);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(11, 13, NULL, 2587);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(12, 12, NULL, 287);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(13, 14, NULL, 854);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(14, 2, NULL, 2);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(15, 2, NULL, 5);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(16, 1, NULL, 52);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(17, 1, NULL, 35);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(18, NULL, 4, 25);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(19, NULL, 2, 10000);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(20, NULL, 7, 5);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(21, NULL, 5, 240);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(22, NULL, 10, 9875);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(23, NULL, 9, 1250);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(24, 9, NULL, 32);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(25, 10, NULL, 52);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(26, 11, NULL, 95);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(27, 12, NULL, 115);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(28, 13, NULL, 185);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(29, 2, NULL, 258);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(30, 16, NULL, 365);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(31, 5, NULL, 456);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(32, 2, NULL, 756);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(33, 15, NULL, 725);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(34, 4, NULL, 689);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(35, NULL, 4, 1);
INSERT INTO CONCERNER(CONC_IDCOMMANDE, CONC_IDCOMPOSITION, CONC_IDFLEUR, CONC_QUANTITE)
  VALUES(36, NULL, 2, 1);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(1, 4, 30);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(1, 6, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(1, 1, 21);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(1, 5, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(1, 8, 15);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(2, 2, 21);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(3, 3, 30);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(3, 8, 15);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(3, 5, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(3, 7, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(3, 9, 25);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(4, 6, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(4, 3, 30);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(4, 9, 26);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(4, 8, 15);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(5, 7, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(5, 8, 15);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(5, 4, 30);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(5, 6, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(5, 7, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(5, 5, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(6, 13, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(6, 11, 30);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(6, 12, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(6, 15, 15);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(8, 10, 30);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(8, 16, 25);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(8, 15, 15);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(8, 14, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(8, 12, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(9, 14, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(9, 13, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(9, 10, 30);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(9, 15, 15);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(9, 16, 26);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(10, 12, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(10, 15, 15);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(10, 11, 30);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(10, 13, 20);
INSERT INTO CONTENIR(CONT_IDFLEUR, CONT_IDCOMPOSITION, CONT_QUANTITE)
  VALUES(10, 14, 20);
